### ISSUE TITLE
Loading Issue on 41.60 MP Dedicated Server

### ISSUE THREAD

**Issue by DaNeo61** [ibrrus/tsarslib#2]
I Just wanna inform you maybe its usefull, awesome Mods, keep it going !!

> LOG  : Lua         , 1639141812951> 30.553.272> Loading: steamapps/workshop/content/108600/2392709985/mods/Tsar Common 
> Library/media/lua/server/Items/ATACommonItemDistributions.lua
> LOG  : General     , 1639141812952> 30.553.273> -------------------------------------------------------------
> attempted index: items of non-table: null
> 
> LOG  : General     , 1639141812952> 30.553.273> -----------------------------------------
> STACK TRACE
> -----------------------------------------
> function: ATACommonItemDistributions.lua -- file: ATACommonItemDistributions.lua line # 61
> 
> ERROR: General     , 1639141812952> 30.553.273> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: items of non-table: null at KahluaThread.tableget line:1689.
> ERROR: General     , 1639141812952> 30.553.273> DebugLogStream.printException> Stack trace:
> java.lang.RuntimeException: attempted index: items of non-table: null
> 	at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
> 	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
> 	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
> 	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
> 	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1782)
> 	at se.krka.kahlua.integration.LuaCaller.pcall(LuaCaller.java:76)
> 	at se.krka.kahlua.integration.LuaCaller.protectedCall(LuaCaller.java:117)
> 	at zombie.Lua.LuaManager.RunLuaInternal(LuaManager.java:549)
> 	at zombie.Lua.LuaManager.RunLua(LuaManager.java:495)
> 	at zombie.Lua.LuaManager.RunLua(LuaManager.java:481)
> 	at zombie.Lua.LuaManager.LoadDirBase(LuaManager.java:328)
> 	at zombie.Lua.LuaManager.LoadDirBase(LuaManager.java:255)
> 	at zombie.network.GameServer.doMinimumInit(GameServer.java:1368)
> 	at zombie.network.GameServer.main(GameServer.java:665)
> LOG  : General     , 1639141812952> 30.553.273> -----------------------------------------
> STACK TRACE
> -----------------------------------------
> function: ATACommonItemDistributions.lua -- file: ATACommonItemDistributions.lua line # 61
> 
> Dez. 10, 2021 2:10:12 PM zombie.Lua.LuaManager RunLuaInternal
> SCHWERWIEGEND:  java.lang.RuntimeException
> Dez. 10, 2021 2:10:12 PM zombie.Lua.LuaManager RunLuaInternal
> SCHWERWIEGEND: java.lang.RuntimeException: 
> Dez. 10, 2021 2:10:12 PM zombie.Lua.LuaManager RunLuaInternal
> SCHWERWIEGEND: at ATACommonItemDistributions.lua:61
> 
> LOG  : Lua         , 1639141812953> 30.553.274> Loading: steamapps/workshop/content/108600/2636100523/mods/AutotsarTuning_Jeep/media/lua/server/Items/ATAJeep_ItemDistributions.lua
> LOG  : General     , 1639141812954> 30.553.274> -------------------------------------------------------------
> attempted index: items of non-table: null
> 
> LOG  : General     , 1639141812954> 30.553.274> -----------------------------------------
> STACK TRACE
> -----------------------------------------
> function: ATAJeep_ItemDistributions.lua -- file: ATAJeep_ItemDistributions.lua line # 5
> 
> ERROR: General     , 1639141812954> 30.553.274> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: items of non-table: null at KahluaThread.tableget line:1689.
> ERROR: General     , 1639141812954> 30.553.274> DebugLogStream.printException> Stack trace:
> java.lang.RuntimeException: attempted index: items of non-table: null
> 	at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
> 	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
> 	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
> 	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
> 	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1782)
> 	at se.krka.kahlua.integration.LuaCaller.pcall(LuaCaller.java:76)
> 	at se.krka.kahlua.integration.LuaCaller.protectedCall(LuaCaller.java:117)
> 	at zombie.Lua.LuaManager.RunLuaInternal(LuaManager.java:549)
> 	at zombie.Lua.LuaManager.RunLua(LuaManager.java:495)
> 	at zombie.Lua.LuaManager.RunLua(LuaManager.java:481)
> 	at zombie.Lua.LuaManager.LoadDirBase(LuaManager.java:328)
> 	at zombie.Lua.LuaManager.LoadDirBase(LuaManager.java:255)
> 	at zombie.network.GameServer.doMinimumInit(GameServer.java:1368)
> 	at zombie.network.GameServer.main(GameServer.java:665)
> LOG  : General     , 1639141812954> 30.553.275> -----------------------------------------
> STACK TRACE
> -----------------------------------------
> function: ATAJeep_ItemDistributions.lua -- file: ATAJeep_ItemDistributions.lua line # 5
> 
> Dez. 10, 2021 2:10:12 PM zombie.Lua.LuaManager RunLuaInternal
> SCHWERWIEGEND:  java.lang.RuntimeException
> Dez. 10, 2021 2:10:12 PM zombie.Lua.LuaManager RunLuaInternal
> SCHWERWIEGEND: java.lang.RuntimeException: 
> Dez. 10, 2021 2:10:12 PM zombie.Lua.LuaManager RunLuaInternal
> SCHWERWIEGEND: at ATAJeep_ItemDistributions.lua:5

Sorry the formating is bad on Github

**Comment by ibrrus** [comment]
Fixed
